name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        uses: pierdipi/unicode-control-characters-action@main
        with:
          args: -d .
